Repository JNU-econovation/jnu-wiki-fe, pull requests merged in 2023-11, with the labels that each got.

#116 refactor: mutation 커스텀 훅, alert/toast 함수 분리, 사이드바 prop 변경
  src/components/common/layout/Header.jsx
  src/components/common/layout/MainLayout.jsx
  src/components/common/layout/MypageSidebar.jsx
  src/components/common/layout/Sidebar.jsx
  src/components/common/layout/SidebarList.jsx
  src/components/document/CreateDocument.jsx
  src/components/document/DocsItem.jsx
  src/components/document/DocsList.jsx
  src/components/document/Document.jsx
  src/components/mypage/MypageScrap.jsx
  src/components/mypage/ScrapList.jsx
  src/components/search/SearchBar.jsx
  src/constant/helpermsg.js
  src/hooks/useDocsMutation.js
  src/hooks/useValidation.js
  src/index.css
  src/pages/AddPost.jsx
  src/pages/DocumentListPage.jsx
  src/pages/DocumentPage.jsx
  src/pages/MyInfoEdit.jsx
  src/pages/MyPage.jsx
  src/pages/Scrap.jsx
  src/styles/globalStyle.jsx
  src/utils/alert.js
  src/utils/handlePasswordVisible.jsx
  src/utils/toast.js
Labels: bug, fix

#123 docs: 리드미 수정
  README.md
  src/components/common/form/RegisterForm.jsx
Labels: bug, documentation

#124 docs: README.md 업데이트
  README.md
  src/components/common/form/RegisterForm.jsx
Labels: documentation

#126 fix: 로그인 수정
  package-lock.json
  package.json
  src/components/common/form/LoginForm.jsx
  src/components/common/layout/Header.jsx
  src/services/index.jsx
  src/services/user.jsx
  src/utils/CookieFunc.js
Labels: bug, enhancement

#127 refactor: 코드리뷰 코드 수정
  src/components/common/form/LoginForm.jsx
  src/components/common/form/MyInfoEditForm.jsx
  src/components/common/layout/Header.jsx
  src/main.jsx
  src/services/index.jsx
  src/utils/CookieFunc.js
  src/utils/alert.js
Labels: bug, 🔨 fix
