Repository JNU-econovation/jnu-wiki-fe, pull requests merged in 2023-09, with the labels that each got.

#80 feat: 문서 상세 조회 스크랩 기능 추가
  src/components/common/document/DocsList.jsx
  src/components/common/document/Document.jsx
  src/components/common/document/ScrapBtn.jsx
Labels: enhancement

#84 fix: 새 문서 생성 요청 완료 시 입력창 초기화
  src/components/common/document/CreateDocument.jsx
  src/components/common/document/DocsList.jsx
  src/components/common/document/Document.jsx
  src/components/common/document/DocumentHeading.jsx
Labels: bug, fix

#85 feat: 문서 접는 기능 추가
  src/components/common/document/CreateDocument.jsx
  src/components/common/document/Document.jsx
  src/components/common/document/ToggleBtn.jsx
  src/pages/DocumentListPage.jsx
  src/pages/DocumentPage.jsx
Labels: enhancement

#91 feat: 검색창 디자인 변경
  public/main-logo.png
  src/components/common/document/Document.jsx
  src/components/common/document/ToggleBtn.jsx
  src/components/common/layout/Header.jsx
  src/components/common/layout/Map.jsx
  src/components/common/search/SearchBar.jsx
  src/components/common/search/SearchData.jsx
  src/components/search/Search.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchItem.jsx
  src/pages/DocumentListPage.jsx
  src/services/document.jsx
  src/store/boundReducer.js
  src/store/index.js
Labels: enhancement, fix

#92 fix: 헤더 아이콘 위치 수정
  src/components/common/layout/Header.jsx
  src/components/search/SearchBar.jsx
Labels: fix

#94 fix: 헤더 넓이 변경
  src/components/common/layout/Header.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchItem.jsx
Labels: fix

#93 feat: 어드민 reload
  src/components/common/admin/RequestContain.jsx
  src/components/common/admin/TitleBox.jsx
  src/components/common/layout/Header.jsx
Labels: fix

#96 fix:documentPage_lnglat
  src/pages/DocumentPage.jsx
Labels: fix

#100 feat: 레이아웃 변경
  src/components/common/layout/Header.jsx
  src/components/common/layout/Sidebar.jsx
  src/components/document/CreateDocument.jsx
  src/components/document/Document.jsx
  src/components/document/DocumentHeading.jsx
  src/components/document/DocumentTime.jsx
  src/components/document/InfoGroup.jsx
  src/components/document/ScrapBtn.jsx
  src/components/document/ToggleBtn.jsx
Labels: enhancement
