Repository JNU-econovation/jnu-wiki-fe, pull requests merged in 2024-04, with the labels that each got.

#152 refactor: 검색 결과가 잘 이동하지 못하는 문제를 해결한다.
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/DocumentTime.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchItem.jsx
  src/hooks/useHandleClickOutside.js
  src/index.css
  src/services/index.jsx
Labels: 🔨 fix, ✨ refactor

#154 fix: 문서 편집 시간 반영
  src/components/document/Content.jsx
Labels: 🔨 fix

#156 docs: pr 템플릿 수정
  .github/pull_request_template.md
Labels: documentation, 🔨 fix

#158 fix: inputGroup 에러메세지 수정
  src/components/common/Input/InputGroup.jsx
  src/utils/registerRules.js
Labels: bug

#161 fix: 문서, 레이아웃에 시맨틱 태그 적용
  src/components/Map/MainMap.jsx
  src/components/Map/Map.jsx
  src/components/common/button/HeaderButtons.jsx
  src/components/common/button/ScrapBtn.jsx
  src/components/common/button/ToggleBtn.jsx
  src/components/common/layout/Header.jsx
  src/components/common/layout/List.jsx
  src/components/common/layout/Loader.jsx
  src/components/common/layout/MainLayout.jsx
  src/components/common/layout/MypageSidebar.jsx
  src/components/common/layout/Profile.jsx
  src/components/common/layout/Sidebar.jsx
  src/components/common/layout/SidebarList.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/createDocument/DocumentInputGroup.jsx
  src/components/docsList/DocsItem.jsx
  src/components/docsList/DocumentWrapper.jsx
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/Document.jsx
  src/components/document/DocumentTime.jsx
  src/components/search/SearchBar.jsx
  src/pages/AddPost.jsx
  src/styles/DocsList.jsx
  src/styles/StyledInput.jsx
Labels: 🔨 fix, ✨ refactor

#165 refactor: 지도 관련 컴포넌트 리팩토링
  src/components/Map/MainMap.jsx
  src/components/Map/Map.jsx
  src/components/Map/MapWithClickEvent.jsx
  src/hooks/useInfiniteScroll.js
  src/pages/AddPost.jsx
  src/pages/DocumentPage.jsx
  src/services/index.jsx
Labels: ✨ refactor

#166 refactor: 문서 상세 조회 리팩토링
  src/components/Map/MapWithClickEvent.jsx
  src/components/common/button/ScrapBtn.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/createDocument/DocumentInputGroup.jsx
  src/components/docsList/DocsItem.jsx
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/DocumentHeading.jsx
  src/components/document/DocumentLabel.jsx
  src/hooks/useDocsMutation.js
  src/hooks/useScrap.js
  src/services/index.jsx
  src/store/editReducer.js
  src/store/index.js
Labels: ✨ refactor

#167 refactor: 검색 API 요청 횟수 줄이기
  src/components/search/SearchBar.jsx
  src/hooks/useSearch.js
  src/hooks/useSearchQuery.js
Labels: ✨ refactor

#170 refactor: 문서 생성 리팩토링
  src/components/Map/MainMap.jsx
  src/components/Map/MapWithClickEvent.jsx
  src/components/common/button/Button.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/DocumentHeading.jsx
  src/hooks/useHandleAddress.js
  src/pages/AddPost.jsx
  src/pages/BasicInfoEditReq.jsx
  src/pages/DocumentPage.jsx
  src/pages/NewDocsReq.jsx
Labels: ✨ refactor

#172 fix: 기본정보 편집 후 input에 계속 캐싱되어 있는 문제 해결
  src/components/Map/MapWithClickEvent.jsx
  src/components/common/layout/Header.jsx
  src/components/document/Basic.jsx
  src/services/document.jsx
Labels: 🔨 fix
