Repository JNU-econovation/jnu-wiki-fe, pull requests merged in 2024-01, with the labels that each got.

#136 style: 폰트 크기, 넓이 등 스타일 변경
  jsconfig.json
  src/components/common/Input/SelectInput.jsx
  src/components/common/button/ScrapBtn.jsx
  src/components/common/button/ToggleBtn.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/createDocument/DocumentInput.jsx
  src/components/createDocument/DocumentInputGroup.jsx
  src/components/docsList/DocsItem.jsx
  src/components/docsList/DocsList.jsx
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/Document.jsx
  src/components/document/DocumentHeading.jsx
  src/components/document/DocumentLabel.jsx
  src/components/document/DocumentTime.jsx
  src/components/document/ErrorMsg.jsx
  src/components/mypage/ScrapList.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchItem.jsx
  src/hooks/useHandleAddress.js
  src/pages/DocumentPage.jsx
  src/styles/DocsItem.jsx
  src/styles/DocsList.jsx
  src/styles/StyledInput.jsx
  vite.config.js
Labels: ✨ refactor

#140 style: 반응형 구현
  src/App.jsx
  src/components/Map/MainMap.jsx
  src/components/Map/Map.jsx
  src/components/common/Input/InputGroup.jsx
  src/components/common/button/ToggleBtn.jsx
  src/components/common/form/LoginForm.jsx
  src/components/common/form/RegisterForm.jsx
  src/components/common/layout/Header.jsx
  src/components/common/layout/MainLayout.jsx
  src/components/common/layout/Sidebar.jsx
  src/components/common/layout/SidebarList.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/createDocument/DocumentInputGroup.jsx
  src/components/docsList/DocumentWrapper.jsx
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/Document.jsx
  src/components/document/DocumentHeading.jsx
  src/components/document/DocumentLabel.jsx
  src/components/register/Container.jsx
  src/components/register/Label.jsx
  src/components/register/Question.jsx
  src/components/register/Title.jsx
  src/components/search/SearchBar.jsx
  src/hooks/useScrap.js
  src/index.css
  src/pages/DocumentListPage.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/styles/DocsItem.jsx
  src/styles/DocsList.jsx
  src/styles/StyledInput.jsx
Labels: 🔥 enhancement

#142 refactor : 마이페이지 하단바 수정
  .github/workflows/deploy.yml
  src/components/common/Icon.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/InputGroup.jsx
  src/components/common/Logout.jsx
  src/components/common/form/LoginForm.jsx
  src/components/common/form/MyInfoEditForm.jsx
  src/components/common/form/MypageForm.jsx
  src/components/common/form/RegisterForm.jsx
  src/components/common/layout/Header.jsx
  src/components/common/layout/MypageBottom.jsx
  src/components/common/layout/SidebarList.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/document/Document.jsx
  src/components/register/Box.jsx
  src/components/register/Button.jsx
  src/components/register/Container.jsx
  src/components/register/Title.jsx
  src/services/index.jsx
  src/styles/DocsList.jsx
  src/styles/InputForm.js
Labels: 🔨 fix, ✨ refactor

#145 fix: 자잘한 에러 수정
  index.html
  public/fonts/pretendard.css
  src/components/Map/MainMap.jsx
  src/components/common/button/Button.jsx
  src/components/common/layout/SidebarList.jsx
  src/components/createDocument/CreateDocument.jsx
  src/components/createDocument/DocumentInputGroup.jsx
  src/components/docsList/DocsItem.jsx
  src/components/docsList/DocsList.jsx
  src/components/document/Basic.jsx
  src/components/document/Content.jsx
  src/components/document/Document.jsx
  src/components/document/DocumentHeading.jsx
  src/components/mypage/MypageScrap.jsx
  src/components/mypage/ScrapList.jsx
  src/components/search/SearchBar.jsx
  src/hooks/useBottomDisplay.js
  src/hooks/useHandleAddress.js
  src/hooks/useHandleSearchBar.js
  src/hooks/useSearch.js
  src/hooks/useSearchQuery.js
  src/styles/globalStyle.jsx
Labels: bug, 🔨 fix
